//photographs
export const GOT_ALL_PHOTOGRAPHS = 'GOT_ALL_PHOTOGRAPHS'

export const GOT_ONE_PHOTOGRAPH = 'GOT_ONE_PHOTOGRAPH'

export const ADDED_PHOTOGRAPH = 'ADDED_PHOTOGRAPH'

export const REMOVED_PHOTOGRAPH = 'REMOVED_PHOTOGRAPH'

export const UPDATED_PHOTOGRAPH = 'UPDATED_PHOTOGRAPH'


//artists
export const GOT_ALL_ARTISTS = 'GOT_ALL_ARTISTS'

export const GOT_ONE_ARTIST = 'GOT_ONE_ARTIST'

export const ADDED_ARTIST = 'ADDED_ARTIST'

export const REMOVED_ARTIST = 'REMOVED_ARTIST'

export const UPDATED_ARTIST = 'UPDATED_ARTIST'
